# Generated by Django 5.2.8 on 2025-11-30 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloUtente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profilo', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
                ('ruolo', models.CharField(choices=[('ADMIN', 'Amministratore'), ('GESTORE_MAGAZZINO', 'Gestore Magazzino'), ('OPERATORE', 'Operatore'), ('VISUALIZZATORE', 'Visualizzatore')], default='OPERATORE', help_text="Ruolo dell'utente nel sistema", max_length=20, verbose_name='Ruolo')),
                ('dipartimento', models.CharField(blank=True, help_text='Dipartimento di appartenenza', max_length=100, null=True, verbose_name='Dipartimento')),
                ('numero_dipendente', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numero Dipendente')),
                ('attivo', models.BooleanField(default=True, help_text='Utente attivo o disattivato', verbose_name='Attivo')),
                ('ultimo_accesso', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultimo Accesso')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data Modifica')),
            ],
            options={
                'verbose_name': 'Profilo Utente',
                'verbose_name_plural': 'Profili Utenti',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='LogAccesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_accesso', models.DateTimeField(auto_now_add=True, verbose_name='Data Accesso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP')),
                ('user_agent', models.TextField(blank=True, help_text='Browser e sistema operativo', null=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, help_text="Indica se l'accesso è stato riuscito", verbose_name='Accesso Riuscito')),
                ('motivo_fallimento', models.CharField(blank=True, help_text="Motivo del fallimento dell'accesso", max_length=255, null=True, verbose_name='Motivo Fallimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessi', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Log Accesso',
                'verbose_name_plural': 'Log Accessi',
                'db_table': 'log_accessi',
                'ordering': ['-data_accesso'],
                'indexes': [models.Index(fields=['-data_accesso'], name='log_accessi_data_ac_fcc71b_idx'), models.Index(fields=['user', '-data_accesso'], name='log_accessi_user_id_ba5464_idx')],
            },
        ),
    ]
