"""
Django settings for GESTIONE MAGAZZINO RICAMBI.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# SECURITY SETTINGS
# ============================================================================

# Secret Key - IN PRODUZIONE USARE VARIABILI D'AMBIENTE!
SECRET_KEY = 'django-insecure-17jw!z+5t52v@%h7g0x9-hp+9l)b2^caiyphgmeqvyv-^tkj)9'

# Debug mode - IN PRODUZIONE METTERE A FALSE
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.*']

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": ("'self'",),
    "script-src": ("'self'", "'unsafe-inline'"),
    "style-src": ("'self'", "'unsafe-inline'"),
}

# ============================================================================
# APPLICATION DEFINITION
# ============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Nostre app
    'accounts.apps.AccountsConfig',
    'magazzino.apps.MagazzinoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.NoCacheMiddleware',  # Previene cache per utenti autenticati
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ============================================================================
# DATABASE CONFIGURATION - MYSQL
# ============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'GMR',
        'USER': 'root',
        'PASSWORD': '',  # XAMPP di default ha password vuota
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'CHARSET': 'utf8mb4',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# ============================================================================
# PASSWORD VALIDATION E AUTENTICAZIONE
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,  # Password di almeno 10 caratteri
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# PASSWORD HASHING - ARGON2 (più sicuro di PBKDF2)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# ============================================================================
# INTERNATIONALIZATION - ITALIANO
# ============================================================================

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True

# ============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# ============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# ============================================================================
# MEDIA FILES (Upload utenti)
# ============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CRISPY FORMS CONFIGURATION
# ============================================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ============================================================================
# SESSION CONFIGURATION - SICUREZZA
# ============================================================================

SESSION_COOKIE_SECURE = False  # Mettere True in HTTPS
SESSION_COOKIE_HTTPONLY = True  # Impedisce accesso da JavaScript
SESSION_COOKIE_SAMESITE = 'Strict'  # Protezione CSRF aggiuntiva
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session scade alla chiusura del browser
SESSION_COOKIE_AGE = 3600  # 1 ora in secondi

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Crea cartella logs se non esiste
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# ============================================================================
# MARIADB 10.4 COMPATIBILITY (XAMPP Default)
# ============================================================================
# Supporta MariaDB 10.4 disabilitando il check della versione

import django.db.backends.mysql.base
def patched_check(self):
    """Consenti MariaDB 10.4+"""
    pass

django.db.backends.mysql.base.DatabaseWrapper.check_database_version_supported = patched_check

# Disabilita RETURNING per MariaDB 10.4 (non supportato)
django.db.backends.mysql.base.DatabaseFeatures.can_return_columns_from_insert = False

# ============================================================================
# BACKUP SETTINGS (Caricati da database al runtime)
# ============================================================================
# Le configurazioni di backup vengono lette dalla tabella 'configurazioni'
# Questi sono solo valori di fallback se il database non è ancora inizializzato
BACKUP_DIR = BASE_DIR / 'backups'
BACKUP_RETENTION_DAYS = 30
MYSQL_BIN_PATH = r'C:\xampp\mysql\bin'

# ============================================================================
# MEDIA FILES (Upload immagini articoli)
# ============================================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Per il futuro: migrazione su NAS Synology
# MEDIA_ROOT = Path(r'\\NAS-SYNOLOGY\magazzino\media')  # Percorso UNC via VPN
