# Generated by Django 5.2.8 on 2025-11-30 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(help_text='Inserire il nome della categoria (es. Meccanica, Elettrica)', max_length=50, unique=True, verbose_name='Nome Categoria')),
                ('descrizione', models.CharField(blank=True, help_text='Descrizione tecnica della categoria', max_length=200, null=True, verbose_name='Descrizione')),
                ('stato_attivo', models.BooleanField(default=True, help_text='Categoria attiva o disattivata', verbose_name='Stato Attivo')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('modificato_il', models.DateTimeField(auto_now=True, db_column='modificato_il')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'db_table': 'categorie',
                'ordering': ['nome_categoria'],
                'indexes': [models.Index(fields=['stato_attivo'], name='categorie_stato_a_d7faa2_idx'), models.Index(fields=['nome_categoria'], name='categorie_nome_ca_fafdc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAllegato',
            fields=[
                ('id_documento', models.AutoField(db_column='id_documento', primary_key=True, serialize=False)),
                ('tipo_entita', models.CharField(choices=[('ARTICOLO', 'Articolo'), ('MOVIMENTO', 'Movimento'), ('FORNITORE', 'Fornitore')], db_column='tipo_entita', max_length=20, verbose_name='Tipo Entità')),
                ('id_entita', models.IntegerField(db_column='id_entita', help_text="ID dell'articolo, movimento o fornitore", verbose_name='ID Entità')),
                ('tipo_documento', models.CharField(blank=True, help_text='Fattura, scheda tecnica, manuale, ecc.', max_length=50, null=True, verbose_name='Tipo Documento')),
                ('nome_file', models.CharField(db_column='nome_file', max_length=150, verbose_name='Nome File')),
                ('percorso_file', models.CharField(db_column='percorso_file', max_length=250, verbose_name='Percorso File')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, db_column='data_caricamento', verbose_name='Data Caricamento')),
                ('operatore', models.CharField(blank=True, help_text='Username di chi ha caricato il file', max_length=50, null=True, verbose_name='Operatore')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Documento Allegato',
                'verbose_name_plural': 'Documenti Allegati',
                'db_table': 'documenti_allegati',
                'ordering': ['-data_caricamento'],
                'indexes': [models.Index(fields=['tipo_entita', 'id_entita'], name='documenti_a_tipo_en_d4284d_idx'), models.Index(fields=['tipo_documento'], name='documenti_a_tipo_do_47e138_idx'), models.Index(fields=['data_caricamento'], name='documenti_a_data_ca_9970d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id_fornitore', models.AutoField(db_column='id_fornitore', primary_key=True, serialize=False)),
                ('ragione_sociale', models.CharField(help_text="Nome dell'azienda fornitrice", max_length=100, verbose_name='Ragione Sociale')),
                ('indirizzo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Indirizzo')),
                ('citta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Città')),
                ('cap', models.CharField(blank=True, max_length=10, null=True, verbose_name='CAP')),
                ('provincia', models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('partita_iva', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Partita IVA')),
                ('tempo_medio_consegna_giorni', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Tempo Medio Consegna (giorni)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('stato_attivo', models.BooleanField(default=True, verbose_name='Stato Attivo')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('modificato_il', models.DateTimeField(auto_now=True, db_column='modificato_il')),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'db_table': 'fornitori',
                'ordering': ['ragione_sociale'],
                'indexes': [models.Index(fields=['ragione_sociale'], name='fornitori_ragione_1c70dd_idx'), models.Index(fields=['partita_iva'], name='fornitori_partita_b245ba_idx'), models.Index(fields=['stato_attivo'], name='fornitori_stato_a_0c71e2_idx'), models.Index(fields=['email'], name='fornitori_email_2422a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='id_inventario', primary_key=True, serialize=False)),
                ('data_inventario', models.DateField(db_column='data_inventario', verbose_name='Data Inventario')),
                ('operatore', models.CharField(help_text="Chi ha effettuato l'inventario", max_length=50, verbose_name='Operatore')),
                ('stato', models.CharField(choices=[('IN_CORSO', 'In Corso'), ('CHIUSO', 'Chiuso'), ('APPROVATO', 'Approvato')], db_column='stato', default='IN_CORSO', max_length=20, verbose_name='Stato')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('modificato_il', models.DateTimeField(auto_now=True, db_column='modificato_il')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventari',
                'db_table': 'inventari',
                'ordering': ['-data_inventario'],
                'indexes': [models.Index(fields=['data_inventario'], name='inventari_data_in_0f78f5_idx'), models.Index(fields=['stato'], name='inventari_stato_e445c1_idx'), models.Index(fields=['operatore'], name='inventari_operato_87a52a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitaMisura',
            fields=[
                ('id_unita', models.AutoField(db_column='id_unita', primary_key=True, serialize=False)),
                ('codice', models.CharField(help_text='Codice univoco (es. pz, kg, mt, lt)', max_length=10, unique=True, verbose_name='Codice')),
                ('descrizione', models.CharField(help_text="Descrizione estesa dell'unità", max_length=50, verbose_name='Descrizione')),
                ('stato_attivo', models.BooleanField(default=True, verbose_name='Stato Attivo')),
            ],
            options={
                'verbose_name': 'Unità di Misura',
                'verbose_name_plural': 'Unità di Misura',
                'db_table': 'unita_misura',
                'ordering': ['descrizione'],
                'indexes': [models.Index(fields=['codice'], name='unita_misur_codice_c664fe_idx'), models.Index(fields=['stato_attivo'], name='unita_misur_stato_a_caea71_idx')],
            },
        ),
        migrations.CreateModel(
            name='PezzoRicambio',
            fields=[
                ('id_articolo', models.AutoField(db_column='id_articolo', primary_key=True, serialize=False)),
                ('codice_interno', models.CharField(help_text="Codice interno univoco dell'articolo", max_length=50, unique=True, verbose_name='Codice Interno')),
                ('codice_scm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice SCM')),
                ('codice_fornitore', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice Fornitore')),
                ('codice_alternativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice Alternativo')),
                ('descrizione', models.CharField(help_text="Descrizione estesa dell'articolo", max_length=200, verbose_name='Descrizione')),
                ('giacenza_minima', models.IntegerField(default=5, help_text='Soglia minima di riordino', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giacenza Minima')),
                ('giacenza_massima', models.IntegerField(default=100, help_text='Scorta massima consigliata', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giacenza Massima')),
                ('prezzo_acquisto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prezzo Acquisto')),
                ('prezzo_acquisto_scm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prezzo Acquisto SCM')),
                ('stato_attivo', models.BooleanField(default=True, verbose_name='Stato Attivo')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('modificato_il', models.DateTimeField(auto_now=True, db_column='modificato_il')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='magazzino.categoria', verbose_name='Categoria')),
                ('unita_misura', models.ForeignKey(db_column='id_unita_misura', on_delete=django.db.models.deletion.PROTECT, to='magazzino.unitamisura', verbose_name='Unità di Misura')),
            ],
            options={
                'verbose_name': 'Pezzo di Ricambio',
                'verbose_name_plural': 'Pezzi di Ricambio',
                'db_table': 'pezzi_ricambio',
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoMagazzino',
            fields=[
                ('id_movimento', models.AutoField(db_column='id_movimento', primary_key=True, serialize=False)),
                ('data_movimento', models.DateTimeField(auto_now_add=True, db_column='data_movimento', verbose_name='Data Movimento')),
                ('tipo_movimento', models.CharField(choices=[('CARICO', 'Carico'), ('SCARICO', 'Scarico'), ('RETTIFICA', 'Rettifica'), ('RESO_FORNITORE', 'Reso a Fornitore')], db_column='tipo_movimento', max_length=20, verbose_name='Tipo Movimento')),
                ('quantita', models.IntegerField(help_text='Quantità movimentata', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantità')),
                ('causale', models.CharField(blank=True, help_text='Motivo del movimento', max_length=150, null=True, verbose_name='Causale')),
                ('numero_documento', models.CharField(blank=True, help_text='DDT, Fattura, Ordine, ecc.', max_length=50, null=True, verbose_name='Numero Documento')),
                ('operatore', models.CharField(help_text='Username di chi ha registrato il movimento', max_length=50, verbose_name='Operatore')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('fornitore', models.ForeignKey(blank=True, db_column='id_fornitore', null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazzino.fornitore', verbose_name='Fornitore')),
                ('articolo', models.ForeignKey(db_column='id_articolo', on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='magazzino.pezzoricambio', verbose_name='Articolo')),
            ],
            options={
                'verbose_name': 'Movimento Magazzino',
                'verbose_name_plural': 'Movimenti Magazzino',
                'db_table': 'movimenti_magazzino',
                'ordering': ['-data_movimento'],
                'indexes': [models.Index(fields=['articolo'], name='movimenti_m_id_arti_b7cfb1_idx'), models.Index(fields=['data_movimento'], name='movimenti_m_data_mo_74d5e6_idx'), models.Index(fields=['tipo_movimento'], name='movimenti_m_tipo_mo_e4b413_idx'), models.Index(fields=['fornitore'], name='movimenti_m_id_forn_cb2208_idx'), models.Index(fields=['operatore'], name='movimenti_m_operato_53f61e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Giacenza',
            fields=[
                ('id_giacenza', models.AutoField(db_column='id_giacenza', primary_key=True, serialize=False)),
                ('quantita_disponibile', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantità Disponibile')),
                ('quantita_impegnata', models.IntegerField(default=0, help_text='Quantità impegnata per ordini aperti', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantità Impegnata')),
                ('quantita_prenotata', models.IntegerField(default=0, help_text='Quantità prenotata per lavorazioni', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantità Prenotata')),
                ('ultimo_aggiornamento', models.DateTimeField(auto_now=True, db_column='ultimo_aggiornamento', verbose_name='Ultimo Aggiornamento')),
                ('articolo', models.OneToOneField(db_column='id_articolo', on_delete=django.db.models.deletion.CASCADE, related_name='giacenza', to='magazzino.pezzoricambio', verbose_name='Articolo')),
            ],
            options={
                'verbose_name': 'Giacenza',
                'verbose_name_plural': 'Giacenze',
                'db_table': 'giacenze',
                'indexes': [models.Index(fields=['articolo'], name='giacenze_id_arti_0028a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DettaglioInventario',
            fields=[
                ('id_dettaglio', models.AutoField(db_column='id_dettaglio', primary_key=True, serialize=False)),
                ('quantita_rilevata', models.IntegerField(db_column='quantita_rilevata', help_text='Quantità conteggiata fisicamente', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantità Rilevata')),
                ('quantita_sistema', models.IntegerField(db_column='quantita_sistema', help_text='Quantità registrata nel sistema', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantità Sistema')),
                ('note', models.CharField(blank=True, help_text='Note su anomalie o discrepanze', max_length=200, null=True, verbose_name='Note')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='magazzino.inventario', verbose_name='Inventario')),
                ('articolo', models.ForeignKey(db_column='id_articolo', on_delete=django.db.models.deletion.PROTECT, to='magazzino.pezzoricambio', verbose_name='Articolo')),
            ],
            options={
                'verbose_name': 'Dettaglio Inventario',
                'verbose_name_plural': 'Dettagli Inventario',
                'db_table': 'dettaglio_inventario',
                'ordering': ['articolo'],
                'indexes': [models.Index(fields=['inventario'], name='dettaglio_i_id_inve_649f7e_idx'), models.Index(fields=['articolo'], name='dettaglio_i_id_arti_240122_idx')],
                'unique_together': {('inventario', 'articolo')},
            },
        ),
        migrations.AddIndex(
            model_name='pezzoricambio',
            index=models.Index(fields=['codice_interno'], name='pezzi_ricam_codice__04f0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='pezzoricambio',
            index=models.Index(fields=['codice_fornitore'], name='pezzi_ricam_codice__5a2f02_idx'),
        ),
        migrations.AddIndex(
            model_name='pezzoricambio',
            index=models.Index(fields=['categoria'], name='pezzi_ricam_id_cate_30bdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='pezzoricambio',
            index=models.Index(fields=['stato_attivo'], name='pezzi_ricam_stato_a_b9400a_idx'),
        ),
        migrations.AddIndex(
            model_name='pezzoricambio',
            index=models.Index(fields=['descrizione'], name='pezzi_ricam_descriz_d34cca_idx'),
        ),
    ]
