# Generated by Django 5.2.8 on 2025-12-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurazione',
            fields=[
                ('chiave', models.CharField(help_text='Nome univoco della configurazione', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Chiave')),
                ('valore', models.TextField(help_text='Valore della configurazione', verbose_name='Valore')),
                ('tipo_dato', models.CharField(choices=[('string', 'Stringa'), ('integer', 'Numero Intero'), ('boolean', 'Booleano'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo Dato')),
                ('descrizione', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione')),
                ('modificato_il', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('modificato_da', models.CharField(blank=True, max_length=150, null=True, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Configurazione',
                'verbose_name_plural': 'Configurazioni',
                'db_table': 'configurazioni',
                'ordering': ['chiave'],
            },
        ),
    ]
