# Generated by Django 5.2.8 on 2025-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_configurazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzioneUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('tipo_azione', models.CharField(choices=[('CARICO', 'Carico Magazzino'), ('FORNITORE', 'Nuovo Fornitore'), ('ARTICOLO', 'Nuovo Articolo')], max_length=20, verbose_name='Tipo Azione')),
                ('data_azione', models.DateTimeField(auto_now_add=True, verbose_name='Data Azione')),
                ('dettagli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dettagli')),
            ],
            options={
                'verbose_name': 'Azione Utente',
                'verbose_name_plural': 'Azioni Utenti',
                'db_table': 'azioni_utenti',
                'ordering': ['-data_azione'],
                'indexes': [models.Index(fields=['username', 'tipo_azione'], name='azioni_uten_usernam_dcae0a_idx'), models.Index(fields=['data_azione'], name='azioni_uten_data_az_bd8fca_idx')],
            },
        ),
    ]
