# Generated by Django 5.2.8 on 2025-12-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0003_azioneutente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pezzoricambio',
            name='stato_disponibilita',
            field=models.CharField(choices=[('DISP', 'Disponibile in magazzino'), ('ORD', 'Ordinato - In arrivo'), ('ESAU', 'Esaurito - Da riordinare'), ('FP', 'Fuori produzione')], default='DISP', help_text="Indica la disponibilità fisica dell'articolo", max_length=4, verbose_name='Stato Disponibilità'),
        ),
    ]
