# Generated by Django 5.2.8 on 2025-12-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0004_pezzoricambio_stato_disponibilita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pezzoricambio',
            name='codice_alternativo',
        ),
    ]
