# Generated by Django 5.2.8 on 2025-12-06 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_remove_pezzoricambio_codice_alternativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pezzoricambio',
            name='descrizione_scm',
            field=models.CharField(blank=True, help_text='Descrizione del codice SCM', max_length=200, null=True, verbose_name='Descrizione Codice SCM'),
        ),
        migrations.AddField(
            model_name='pezzoricambio',
            name='fornitore',
            field=models.ForeignKey(blank=True, db_column='id_fornitore', help_text='Fornitore associato al prezzo di acquisto', null=True, on_delete=django.db.models.deletion.PROTECT, to='magazzino.fornitore', verbose_name='Fornitore Principale'),
        ),
        migrations.AddField(
            model_name='pezzoricambio',
            name='matricola_macchina_scm',
            field=models.CharField(blank=True, help_text='Numero di matricola della macchina SCM', max_length=100, null=True, verbose_name='Matricola Macchina SCM'),
        ),
        migrations.AddField(
            model_name='pezzoricambio',
            name='modello_macchina_scm',
            field=models.CharField(blank=True, help_text='Modello della macchina SCM', max_length=100, null=True, verbose_name='Modello Macchina SCM'),
        ),
    ]
