# Generated by Django 5.2.8 on 2025-12-06 23:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0006_pezzoricambio_descrizione_scm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatricolaMacchinaSCM',
            fields=[
                ('id_matricola', models.AutoField(db_column='id_matricola', primary_key=True, serialize=False)),
                ('matricola_macchina', models.CharField(help_text='Numero di matricola univoco della macchina', max_length=100, unique=True, verbose_name='Matricola Macchina')),
                ('anno', models.IntegerField(blank=True, help_text='Anno di produzione/installazione', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Anno')),
                ('stato_attivo', models.BooleanField(default=True, verbose_name='Stato Attivo')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('modificato_il', models.DateTimeField(auto_now=True, db_column='modificato_il')),
            ],
            options={
                'verbose_name': 'Matricola Macchina SCM',
                'verbose_name_plural': 'Matricole Macchine SCM',
                'db_table': 'matricole_macchine_scm',
                'ordering': ['modello', 'matricola_macchina'],
            },
        ),
        migrations.AddField(
            model_name='pezzoricambio',
            name='matricola_scm_old',
            field=models.CharField(blank=True, db_column='matricola_macchina_scm', max_length=100, null=True, verbose_name='Matricola Macchina SCM (OLD)'),
        ),
        migrations.AddField(
            model_name='pezzoricambio',
            name='modello_scm_old',
            field=models.CharField(blank=True, db_column='modello_macchina_scm', max_length=100, null=True, verbose_name='Modello Macchina SCM (OLD)'),
        ),
        migrations.AlterField(
            model_name='pezzoricambio',
            name='matricola_macchina_scm',
            field=models.ForeignKey(blank=True, db_column='id_matricola_scm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='magazzino.matricolamacchinascm', verbose_name='Matricola Macchina SCM'),
        ),
        migrations.CreateModel(
            name='ModelloMacchinaSCM',
            fields=[
                ('id_modello', models.AutoField(db_column='id_modello', primary_key=True, serialize=False)),
                ('nome_modello', models.CharField(help_text='Denominazione del modello di macchina SCM', max_length=100, unique=True, verbose_name='Nome Modello')),
                ('gamma', models.CharField(blank=True, help_text='Famiglia/Gamma di appartenenza del modello', max_length=100, null=True, verbose_name='Gamma')),
                ('stato_attivo', models.BooleanField(default=True, verbose_name='Stato Attivo')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il')),
                ('modificato_il', models.DateTimeField(auto_now=True, db_column='modificato_il')),
            ],
            options={
                'verbose_name': 'Modello Macchina SCM',
                'verbose_name_plural': 'Modelli Macchine SCM',
                'db_table': 'modelli_macchine_scm',
                'ordering': ['gamma', 'nome_modello'],
                'indexes': [models.Index(fields=['nome_modello'], name='modelli_mac_nome_mo_3d211a_idx'), models.Index(fields=['gamma'], name='modelli_mac_gamma_a4ad8a_idx'), models.Index(fields=['stato_attivo'], name='modelli_mac_stato_a_c2c066_idx')],
            },
        ),
        migrations.AddField(
            model_name='matricolamacchinascm',
            name='modello',
            field=models.ForeignKey(db_column='id_modello', on_delete=django.db.models.deletion.PROTECT, related_name='matricole', to='magazzino.modellomacchinascm', verbose_name='Modello Macchina'),
        ),
        migrations.AlterField(
            model_name='pezzoricambio',
            name='modello_macchina_scm',
            field=models.ForeignKey(blank=True, db_column='id_modello_scm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='magazzino.modellomacchinascm', verbose_name='Modello Macchina SCM'),
        ),
        migrations.AddIndex(
            model_name='matricolamacchinascm',
            index=models.Index(fields=['matricola_macchina'], name='matricole_m_matrico_a46d35_idx'),
        ),
        migrations.AddIndex(
            model_name='matricolamacchinascm',
            index=models.Index(fields=['modello'], name='matricole_m_id_mode_f582b2_idx'),
        ),
        migrations.AddIndex(
            model_name='matricolamacchinascm',
            index=models.Index(fields=['anno'], name='matricole_m_anno_ea6e62_idx'),
        ),
        migrations.AddIndex(
            model_name='matricolamacchinascm',
            index=models.Index(fields=['stato_attivo'], name='matricole_m_stato_a_da0616_idx'),
        ),
    ]
