# Generated by Django 5.2.8 on 2025-12-07 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0007_matricolamacchinascm_pezzoricambio_matricola_scm_old_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['livello', 'ordine', 'nome_categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, db_column='id_categoria_padre', help_text='Categoria superiore nella gerarchia (lasciare vuoto per macrocategoria)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sottocategorie', to='magazzino.categoria', verbose_name='Categoria Padre'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='livello',
            field=models.IntegerField(default=0, editable=False, help_text='0=Macrocategoria, 1=Categoria, 2=Sottocategoria', verbose_name='Livello'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordine',
            field=models.IntegerField(default=0, help_text='Ordine di visualizzazione (0=primo)', verbose_name='Ordine'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(help_text='Inserire il nome della categoria (es. Meccanica, Elettrica)', max_length=50, verbose_name='Nome Categoria'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['categoria_padre'], name='categorie_id_cate_a1dbda_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['livello'], name='categorie_livello_9702e2_idx'),
        ),
    ]
