# Generated by Django 5.2.8 on 2025-12-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0008_alter_categoria_options_categoria_categoria_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pezzoricambio',
            name='immagine',
            field=models.ImageField(blank=True, help_text="Carica un'immagine dell'articolo (max 5MB, formati: JPG, PNG, WebP)", null=True, upload_to='articoli/%Y/%m/', verbose_name='Immagine Articolo'),
        ),
        migrations.AddField(
            model_name='pezzoricambio',
            name='immagine_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Miniatura generata automaticamente (300x300px)', null=True, upload_to='articoli/thumbnails/%Y/%m/', verbose_name='Thumbnail'),
        ),
    ]
