# Generated by Django 5.2.8 on 2025-12-10 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0009_pezzoricambio_immagine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azioneutente',
            name='tipo_azione',
            field=models.CharField(choices=[('CARICO', 'Carico Magazzino'), ('FORNITORE', 'Nuovo Fornitore'), ('ARTICOLO', 'Nuovo Articolo'), ('IMMAGINE', 'Aggiunta Immagine')], max_length=20, verbose_name='Tipo Azione'),
        ),
        migrations.AlterField(
            model_name='pezzoricambio',
            name='codice_scm',
            field=models.CharField(blank=True, help_text='Codice SCM univoco: 10 cifre + 1 lettera maiuscola (es. 1234567890A)', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Il Codice SCM deve essere formato da 10 cifre seguite da 1 lettera maiuscola (es. 1234567890A)', regex='^\\d{10}[A-Z]$')], verbose_name='Codice SCM'),
        ),
    ]
