# Generated by Django 5.2.8 on 2025-12-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0010_alter_azioneutente_tipo_azione_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitamisura',
            options={'ordering': ['descrizione'], 'verbose_name': 'Unità di Misura (Vecchia)', 'verbose_name_plural': 'Unità di Misura (Vecchie)'},
        ),
        migrations.CreateModel(
            name='TbUnitaMisura',
            fields=[
                ('id_unita_misura', models.AutoField(db_column='idUnitaMisura', primary_key=True, serialize=False)),
                ('denominazione', models.CharField(help_text='Nome breve unità (es. Ore, gg, km, Pz)', max_length=50, verbose_name='Denominazione')),
                ('denominazione_stampa', models.CharField(blank=True, help_text='Descrizione completa per stampe (es. "per Ora o frazione")', max_length=100, null=True, verbose_name='Denominazione Stampa')),
                ('stato_attivo', models.BooleanField(default=True, verbose_name='Stato Attivo')),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_column='creato_il', null=True)),
                ('modificato_il', models.DateTimeField(auto_now=True, db_column='modificato_il', null=True)),
            ],
            options={
                'verbose_name': 'Unità di Misura',
                'verbose_name_plural': 'Unità di Misura',
                'db_table': 'tbUnitaMisura',
                'ordering': ['denominazione'],
                'indexes': [models.Index(fields=['denominazione'], name='tbUnitaMisu_denomin_991c5d_idx'), models.Index(fields=['stato_attivo'], name='tbUnitaMisu_stato_a_9a0539_idx')],
            },
        ),
    ]
