# Generated by Django 5.2.8 on 2025-12-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0011_alter_unitamisura_options_tbunitamisura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pezzoricambio',
            name='tb_unita_misura',
            field=models.ForeignKey(blank=True, db_column='id_tb_unita_misura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pezzi_ricambio', to='magazzino.tbunitamisura', verbose_name='Unità di Misura'),
        ),
        migrations.AlterField(
            model_name='pezzoricambio',
            name='unita_misura',
            field=models.ForeignKey(blank=True, db_column='id_unita_misura', help_text='DEPRECATO - Usare tb_unita_misura', null=True, on_delete=django.db.models.deletion.PROTECT, to='magazzino.unitamisura', verbose_name='Unità di Misura (Vecchia)'),
        ),
    ]
