# Generated by Django 5.2.8 on 2025-12-20 14:48

from django.db import migrations


def _trova_colonna_unita_misura(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        descrizione = schema_editor.connection.introspection.get_table_description(cursor, 'pezzi_ricambio')

    colonne = {col.name for col in descrizione}

    for nome_colonna in ('id_unita_misura', 'idUnitaMisura'):
        if nome_colonna in colonne:
            return nome_colonna

    return None


def mappa_vecchie_unita_a_nuove(apps, schema_editor):
    """
    Mappa i vecchi ID unita_misura ai nuovi ID tbUnitaMisura:
    Vecchio → Nuovo:
    1 (Pz) → 9
    2 (L) → 10
    3 (Kg) → 5
    4 (Mt) → 11
    5 (Set) → 12
    6 (Coppia) → 13
    7 (Conf) → 14
    """
    nome_colonna = _trova_colonna_unita_misura(schema_editor)
    if not nome_colonna:
        return

    # Uso SQL diretto perché Django ORM non riconosce il db_column nella migration
    with schema_editor.connection.cursor() as cursor:
        mapping = [
            (1, 9),   # Pz
            (2, 10),  # L → Lt
            (3, 5),   # Kg
            (4, 11),  # Mt
            (5, 12),  # Set
            (6, 13),  # Coppia
            (7, 14),  # Conf
        ]
        
        for vecchio_id, nuovo_id in mapping:
            cursor.execute(
                f"UPDATE pezzi_ricambio SET {nome_colonna} = %s WHERE {nome_colonna} = %s",
                [nuovo_id, vecchio_id]
            )


def reverse_mapping(apps, schema_editor):
    """Reverse mapping per rollback"""
    nome_colonna = _trova_colonna_unita_misura(schema_editor)
    if not nome_colonna:
        return

    with schema_editor.connection.cursor() as cursor:
        mapping = [
            (9, 1),   # Pz
            (10, 2),  # Lt → L
            (5, 3),   # Kg
            (11, 4),  # Mt
            (12, 5),  # Set
            (13, 6),  # Coppia
            (14, 7),  # Conf
        ]
        
        for nuovo_id, vecchio_id in mapping:
            cursor.execute(
                f"UPDATE pezzi_ricambio SET {nome_colonna} = %s WHERE {nome_colonna} = %s",
                [vecchio_id, nuovo_id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0012_pezzoricambio_tb_unita_misura_and_more'),
    ]

    operations = [
        migrations.RunPython(mappa_vecchie_unita_a_nuove, reverse_mapping),
    ]
