# Generated by Django 5.2.8 on 2025-12-20 14:48

from django.db import migrations


def mappa_vecchie_unita_a_nuove(apps, schema_editor):
    """
    Mappa i vecchi ID unita_misura ai nuovi ID tbUnitaMisura:
    Vecchio → Nuovo:
    1 (Pz) → 9
    2 (L) → 10
    3 (Kg) → 5
    4 (Mt) → 11
    5 (Set) → 12
    6 (Coppia) → 13
    7 (Conf) → 14
    """
    # Uso SQL diretto perché Django ORM non riconosce il db_column nella migration
    with schema_editor.connection.cursor() as cursor:
        mapping = [
            (1, 9),   # Pz
            (2, 10),  # L → Lt
            (3, 5),   # Kg
            (4, 11),  # Mt
            (5, 12),  # Set
            (6, 13),  # Coppia
            (7, 14),  # Conf
        ]
        
        for vecchio_id, nuovo_id in mapping:
            cursor.execute(
                "UPDATE pezzi_ricambio SET idUnitaMisura = %s WHERE idUnitaMisura = %s",
                [nuovo_id, vecchio_id]
            )


def reverse_mapping(apps, schema_editor):
    """Reverse mapping per rollback"""
    with schema_editor.connection.cursor() as cursor:
        mapping = [
            (9, 1),   # Pz
            (10, 2),  # Lt → L
            (5, 3),   # Kg
            (11, 4),  # Mt
            (12, 5),  # Set
            (13, 6),  # Coppia
            (14, 7),  # Conf
        ]
        
        for nuovo_id, vecchio_id in mapping:
            cursor.execute(
                "UPDATE pezzi_ricambio SET idUnitaMisura = %s WHERE idUnitaMisura = %s",
                [vecchio_id, nuovo_id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0012_pezzoricambio_tb_unita_misura_and_more'),
    ]

    operations = [
        migrations.RunPython(mappa_vecchie_unita_a_nuove, reverse_mapping),
    ]
