# Generated by Django 5.2.8 on 2025-12-20 14:41

import django.db.models.deletion
from django.db import migrations, models


def rimuovi_tb_unita_misura_field(apps, schema_editor):
    """
    Rimuove il campo id_tb_unita_misura dalla tabella pezzi_ricambio.
    La colonna idUnitaMisura ora punta direttamente a tbUnitaMisura.
    """
    with schema_editor.connection.cursor() as cursor:
        # Rimuovo la FK constraint su id_tb_unita_misura
        cursor.execute("""
            ALTER TABLE pezzi_ricambio 
            DROP FOREIGN KEY pezzi_ricambio_id_tb_unita_misura_9ff4dcae_fk_tbUnitaMi
        """)
        # Rimuovo la colonna id_tb_unita_misura
        cursor.execute("""
            ALTER TABLE pezzi_ricambio 
            DROP COLUMN id_tb_unita_misura
        """)


def ripristina_tb_unita_misura_field(apps, schema_editor):
    """Reverse operation - riaggiunge il campo"""
    with schema_editor.connection.cursor() as cursor:
        # Riaggiungo la colonna id_tb_unita_misura
        cursor.execute("""
            ALTER TABLE pezzi_ricambio 
            ADD COLUMN id_tb_unita_misura INT(11) NULL
        """)
        # Riaggiungo la FK constraint
        cursor.execute("""
            ALTER TABLE pezzi_ricambio 
            ADD CONSTRAINT pezzi_ricambio_id_tb_unita_misura_9ff4dcae_fk_tbUnitaMi 
            FOREIGN KEY (id_tb_unita_misura) REFERENCES tbUnitaMisura(idUnitaMisura)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0013_mappa_unita_misura_vecchie_a_nuove'),
    ]

    operations = [
        migrations.RunPython(rimuovi_tb_unita_misura_field, ripristina_tb_unita_misura_field),
    ]
