# Generated by Django 5.2.8 on 2025-12-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0014_usa_solo_tbunitamisura'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbAppellativo',
            fields=[
                ('id_appellativo', models.AutoField(db_column='idAppellativo', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='Descrizione', help_text='Appellativo (es: Sig., Dott., Prof.)', max_length=50, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Appellativo',
                'verbose_name_plural': 'Appellativi',
                'db_table': 'tbAppellativo',
                'ordering': ['id_appellativo'],
            },
        ),
        migrations.CreateModel(
            name='TbCategoriaIVA',
            fields=[
                ('id_categoria_iva', models.AutoField(db_column='idCategoriaIVA', primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(db_column='NomeCategoria', help_text='Nome categoria IVA (es: Manodopera, Ricambi)', max_length=100, verbose_name='Nome Categoria')),
                ('valore_iva', models.DecimalField(db_column='ValoreIVA', decimal_places=3, help_text='Aliquota IVA (es: 0.22 = 22%, 0 = esente)', max_digits=5, verbose_name='Valore IVA')),
            ],
            options={
                'verbose_name': 'Categoria IVA',
                'verbose_name_plural': 'Categorie IVA',
                'db_table': 'tbCategoriaIVA',
                'ordering': ['nome_categoria'],
            },
        ),
        migrations.CreateModel(
            name='TbCategorieTariffe',
            fields=[
                ('id_categorie_tariffe', models.AutoField(db_column='idCategorieTariffe', primary_key=True, serialize=False)),
                ('categoria_tariffe', models.CharField(db_column='CategoriaTariffe', help_text='Nome categoria (es: Assistenza lunga per cliente generico)', max_length=200, verbose_name='Categoria Tariffe')),
                ('is_visible', models.BooleanField(db_column='IsVisible', default=True, help_text='Visibilità tariffa (attiva/nascosta)', verbose_name='Visibile')),
            ],
            options={
                'verbose_name': 'Categoria Tariffa',
                'verbose_name_plural': 'Categorie Tariffe',
                'db_table': 'tbCategorieTariffe',
                'ordering': ['categoria_tariffe'],
            },
        ),
        migrations.CreateModel(
            name='TbModalitaPagamento',
            fields=[
                ('id_modalita_pagamento', models.AutoField(db_column='idModalitaPagamento', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', help_text='Descrizione modalità (es: Bonifico bancario)', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Modalità Pagamento',
                'verbose_name_plural': 'Modalità Pagamento',
                'db_table': 'tbModalitaPagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TbTipoPagamento',
            fields=[
                ('id_tipo_pagamento', models.AutoField(db_column='idTipoPagamento', primary_key=True, serialize=False)),
                ('descrizione', models.CharField(help_text='Descrizione (es: Bonifico 30 gg D.F.)', max_length=200, verbose_name='Descrizione')),
                ('data_rif_scad', models.CharField(db_column='DataRifScad', help_text='DF=data fattura, FM=fine mese', max_length=50, verbose_name='Riferimento Scadenza')),
                ('giorni_data_rif', models.IntegerField(db_column='GiorniDataRif', help_text='Giorni da aggiungere per scadenza', verbose_name='Giorni da Data Riferimento')),
                ('giorno_addebito', models.IntegerField(db_column='GiornoAddebito', help_text='Giorno specifico addebito (0=nessuno)', verbose_name='Giorno Addebito')),
            ],
            options={
                'verbose_name': 'Tipo Pagamento',
                'verbose_name_plural': 'Tipi Pagamento',
                'db_table': 'tbTipoPagamento',
                'ordering': ['descrizione'],
            },
        ),
    ]
