# Generated by Django 5.2.8 on 2025-12-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0015_tbappellativo_tbcategoriaiva_tbcategorietariffe_and_more'),
    ]

    operations = [
    ]
