# Generated by Django 5.2.8 on 2025-12-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0016_auto_20251223_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbContatti',
            fields=[
                ('id_contatto', models.AutoField(db_column='idContatto', primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, db_column='idCliente', help_text='Riferimento al cliente (FK)', null=True, verbose_name='ID Cliente')),
                ('id_fornitore', models.IntegerField(blank=True, db_column='idFornitore', help_text='Riferimento al fornitore (FK)', null=True, verbose_name='ID Fornitore')),
                ('id_appellativo', models.IntegerField(blank=True, db_column='idAppellativo', help_text="Riferimento all'appellativo (FK)", null=True, verbose_name='ID Appellativo')),
                ('nome', models.CharField(blank=True, help_text='Nome del contatto', max_length=100, verbose_name='Nome')),
                ('cognome', models.CharField(blank=True, help_text='Cognome del contatto', max_length=100, verbose_name='Cognome')),
                ('ruolo', models.CharField(blank=True, help_text="Ruolo del contatto nell'azienda", max_length=100, verbose_name='Ruolo')),
                ('telefono_azienda', models.CharField(blank=True, db_column='TelefonoAzienda', help_text='Telefono aziendale', max_length=50, verbose_name='Telefono Azienda')),
                ('cellulare_azienda', models.CharField(blank=True, db_column='CellulareAzienda', help_text='Cellulare aziendale', max_length=50, verbose_name='Cellulare Azienda')),
                ('email_azienda', models.EmailField(blank=True, db_column='emailAzienda', help_text='Email aziendale', max_length=254, verbose_name='Email Azienda')),
                ('cellulare_personale', models.CharField(blank=True, db_column='CellularePersonale', help_text='Cellulare personale', max_length=50, verbose_name='Cellulare Personale')),
                ('email_personale', models.EmailField(blank=True, db_column='eMailPersonale', help_text='Email personale', max_length=254, verbose_name='Email Personale')),
                ('nota', models.TextField(blank=True, help_text='Note aggiuntive sul contatto', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Contatto',
                'verbose_name_plural': 'Contatti',
                'db_table': 'tbcontatti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='pezzoricambio',
            name='tb_unita_misura',
        ),
        migrations.AlterModelOptions(
            name='unitamisura',
            options={'ordering': ['denominazione'], 'verbose_name': 'Unità di Misura', 'verbose_name_plural': 'Unità di Misura'},
        ),
        migrations.RemoveIndex(
            model_name='unitamisura',
            name='unita_misur_codice_c664fe_idx',
        ),
        migrations.RenameIndex(
            model_name='unitamisura',
            new_name='tbunitamisu_stato_a_712fde_idx',
            old_name='unita_misur_stato_a_caea71_idx',
        ),
        migrations.RemoveField(
            model_name='unitamisura',
            name='codice',
        ),
        migrations.RemoveField(
            model_name='unitamisura',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='unitamisura',
            name='id_unita',
        ),
        migrations.AddField(
            model_name='unitamisura',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, db_column='creato_il', null=True),
        ),
        migrations.AddField(
            model_name='unitamisura',
            name='denominazione',
            field=models.CharField(default='N/A', help_text='Nome breve unità (es. Ore, gg, km, Pz)', max_length=50, verbose_name='Denominazione'),
        ),
        migrations.AddField(
            model_name='unitamisura',
            name='denominazione_stampa',
            field=models.CharField(blank=True, help_text='Descrizione completa per stampe (es. "per Ora o frazione")', max_length=100, null=True, verbose_name='Denominazione Stampa'),
        ),
        migrations.AddField(
            model_name='unitamisura',
            name='id_unita_misura',
            field=models.AutoField(db_column='idUnitaMisura', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unitamisura',
            name='modificato_il',
            field=models.DateTimeField(auto_now=True, db_column='modificato_il', null=True),
        ),
        migrations.AlterField(
            model_name='pezzoricambio',
            name='unita_misura',
            field=models.ForeignKey(db_column='idUnitaMisura', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pezzi_ricambio', to='magazzino.unitamisura', verbose_name='Unità di Misura'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='unitamisura',
            index=models.Index(fields=['denominazione'], name='tbunitamisu_denomin_ffee78_idx'),
        ),
        migrations.AlterModelTable(
            name='tbmodalitapagamento',
            table='tbmodalitapagamento',
        ),
        migrations.AlterModelTable(
            name='tbtipopagamento',
            table='tbtipopagamento',
        ),
        migrations.AlterModelTable(
            name='unitamisura',
            table='tbunitamisura',
        ),
        migrations.DeleteModel(
            name='TbUnitaMisura',
        ),
    ]
