# Generated by Django 5.2.8 on 2025-12-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0017_add_tbcontatti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitamisura',
            name='denominazione',
            field=models.CharField(help_text='Nome breve unità (es. Ore, gg, km, Pz)', max_length=50, verbose_name='Denominazione'),
        ),
        migrations.CreateModel(
            name='TbPrestazioni',
            fields=[
                ('id_prestazione', models.AutoField(db_column='idPrestazione', primary_key=True, serialize=False)),
                ('denominazione', models.CharField(db_column='Denominazione', help_text='Nome della prestazione', max_length=200, verbose_name='Denominazione')),
                ('prezzo_unitario', models.DecimalField(db_column='PrezzoUnitario', decimal_places=2, help_text='Prezzo unitario della prestazione', max_digits=10, verbose_name='Prezzo Unitario')),
                ('visualizza_preventivo', models.BooleanField(db_column='VisualizzaPreventivo', help_text='Se mostrare nel preventivo', verbose_name='Visualizza in Preventivo')),
                ('ordine_stampa', models.IntegerField(blank=True, db_column='OrdineStampa', help_text='Ordine di stampa nel documento', null=True, verbose_name='Ordine Stampa')),
                ('id_categoria_iva', models.ForeignKey(db_column='idCategoriaIVA', help_text='Aliquota IVA applicabile', on_delete=django.db.models.deletion.PROTECT, to='magazzino.tbcategoriaiva', verbose_name='Categoria IVA')),
                ('id_categorie_tariffe', models.ForeignKey(db_column='idCategorieTariffe', help_text='Categoria di tariffa', on_delete=django.db.models.deletion.PROTECT, to='magazzino.tbcategorietariffe', verbose_name='Categoria Tariffe')),
                ('id_unita_misura', models.ForeignKey(db_column='idUnitaMisura', help_text='Unità di misura per la prestazione', on_delete=django.db.models.deletion.PROTECT, to='magazzino.unitamisura', verbose_name='Unità di Misura')),
            ],
            options={
                'verbose_name': 'Prestazione',
                'verbose_name_plural': 'Prestazioni',
                'db_table': 'tbPrestazioni',
                'ordering': ['ordine_stampa', 'denominazione'],
            },
        ),
    ]
