# Generated by Django 5.2.8 on 2026-05-10 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0019_allinea_codici_articolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pezzoricambio',
            name='codice_scm',
            field=models.CharField(blank=True, help_text='Codice SCM univoco: 11 caratteri alfanumerici (es. 07L0320061B)', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Il Codice SCM deve contenere esattamente 11 caratteri alfanumerici (es. 07L0320061B)', regex='^[A-Z0-9]{11}$')], verbose_name='Codice SCM'),
        ),
    ]
